# Generated by Django 4.2.6 on 2023-12-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='email',
            field=models.CharField(default='Capital@gmail.com', max_length=100),
        ),
    ]
