# Generated by Django 4.2.6 on 2023-12-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_capital_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capital',
            name='email',
        ),
    ]
